insert into al_users(email, password, username, role_id) values ('jdoe@gmail.com', '$2a$10$VikgU9SvtQD0gU3C19KTjeQRR4uQI.NRkBFpU8Ok4haEHloBS64rS', 'JDoe', 1);

insert into al_branches(user_id, branch_name) values (null, "main"), (null, "develop"), (null, "master"), (1, "userBranch2");

insert into al_commits(name, branch_id) values 
("CPP-2345 removed comments", 1), 
("CPP-1473 fixed method issue", 2), 
("CPP-4468 added tests", 1), 
("CPP-4682 removed unused imports", 3), 
("CPP-1393 added filter method", 3), 
("CPP-1000 more tests", 4), 
("CPP-5215 controller tests", 4), 
("CPP-2368 removed comment", 1);

insert into al_testsets (name, commit_id) values ('test set 14', 4);
insert into al_testsets (name, commit_id) values ('test set 2', 3);
insert into al_testsets (name, commit_id) values ('test set 15', 6);
insert into al_testsets (name, commit_id) values ('test set 13', 5);
insert into al_testsets (name, commit_id) values ('test set 5', 4);
insert into al_testsets (name, commit_id) values ('test set 12', 5);
insert into al_testsets (name, commit_id) values ('test set 13', 6);
insert into al_testsets (name, commit_id) values ('test set 15', 2);
insert into al_testsets (name, commit_id) values ('test set 7', 6);
insert into al_testsets (name, commit_id) values ('test set 1', 5);
insert into al_testsets (name, commit_id) values ('test set 9', 6);
insert into al_testsets (name, commit_id) values ('test set 1', 5);
insert into al_testsets (name, commit_id) values ('test set 11', 1);
insert into al_testsets (name, commit_id) values ('test set 2', 6);
insert into al_testsets (name, commit_id) values ('test set 3', 4);
insert into al_testsets (name, commit_id) values ('test set 7', 5);
insert into al_testsets (name, commit_id) values ('test set 8', 6);
insert into al_testsets (name, commit_id) values ('test set 14', 3);
insert into al_testsets (name, commit_id) values ('test set 15', 2);
insert into al_testsets (name, commit_id) values ('test set 3', 6);

insert into al_tests (name, test_set_id) values ('test 2', 4);
insert into al_tests (name, test_set_id) values ('test 15', 1);
insert into al_tests (name, test_set_id) values ('test 15', 5);
insert into al_tests (name, test_set_id) values ('test 12', 3);
insert into al_tests (name, test_set_id) values ('test 14', 4);
insert into al_tests (name, test_set_id) values ('test 1', 10);
insert into al_tests (name, test_set_id) values ('test 11', 9);
insert into al_tests (name, test_set_id) values ('test 14', 9);
insert into al_tests (name, test_set_id) values ('test 14', 1);
insert into al_tests (name, test_set_id) values ('test 13', 3);
insert into al_tests (name, test_set_id) values ('test 6', 5);
insert into al_tests (name, test_set_id) values ('test 11', 7);
insert into al_tests (name, test_set_id) values ('test 3', 5);
insert into al_tests (name, test_set_id) values ('test 1', 7);
insert into al_tests (name, test_set_id) values ('test 2', 7);
insert into al_tests (name, test_set_id) values ('test 10', 8);
insert into al_tests (name, test_set_id) values ('test 4', 4);
insert into al_tests (name, test_set_id) values ('test 8', 6);
insert into al_tests (name, test_set_id) values ('test 1', 8);
insert into al_tests (name, test_set_id) values ('test 4', 6);
insert into al_tests (name, test_set_id) values ('test 15', 5);
insert into al_tests (name, test_set_id) values ('test 5', 7);
insert into al_tests (name, test_set_id) values ('test 11', 5);
insert into al_tests (name, test_set_id) values ('test 6', 3);
insert into al_tests (name, test_set_id) values ('test 9', 4);
insert into al_tests (name, test_set_id) values ('test 7', 5);
insert into al_tests (name, test_set_id) values ('test 4', 4);
insert into al_tests (name, test_set_id) values ('test 8', 4);
insert into al_tests (name, test_set_id) values ('test 6', 10);
insert into al_tests (name, test_set_id) values ('test 10', 1);
insert into al_tests (name, test_set_id) values ('test 9', 1);
insert into al_tests (name, test_set_id) values ('test 10', 2);
insert into al_tests (name, test_set_id) values ('test 6', 6);
insert into al_tests (name, test_set_id) values ('test 14', 3);
insert into al_tests (name, test_set_id) values ('test 12', 7);
insert into al_tests (name, test_set_id) values ('test 11', 6);
insert into al_tests (name, test_set_id) values ('test 2', 4);
insert into al_tests (name, test_set_id) values ('test 9', 4);
insert into al_tests (name, test_set_id) values ('test 5', 3);
insert into al_tests (name, test_set_id) values ('test 1', 1);

insert into al_subtests (name, test_result_id) values ('subtest 10', 7);
insert into al_subtests (name, test_result_id) values ('subtest 2', 5);
insert into al_subtests (name, test_result_id) values ('subtest 14', 10);
insert into al_subtests (name, test_result_id) values ('subtest 15', 1);
insert into al_subtests (name, test_result_id) values ('subtest 9', 5);
insert into al_subtests (name, test_result_id) values ('subtest 15', 7);
insert into al_subtests (name, test_result_id) values ('subtest 5', 5);
insert into al_subtests (name, test_result_id) values ('subtest 7', 9);
insert into al_subtests (name, test_result_id) values ('subtest 15', 4);
insert into al_subtests (name, test_result_id) values ('subtest 10', 3);
insert into al_subtests (name, test_result_id) values ('subtest 7', 9);
insert into al_subtests (name, test_result_id) values ('subtest 15', 3);
insert into al_subtests (name, test_result_id) values ('subtest 1', 8);
insert into al_subtests (name, test_result_id) values ('subtest 14', 10);
insert into al_subtests (name, test_result_id) values ('subtest 13', 4);
insert into al_subtests (name, test_result_id) values ('subtest 9', 7);
insert into al_subtests (name, test_result_id) values ('subtest 6', 5);
insert into al_subtests (name, test_result_id) values ('subtest 11', 5);
insert into al_subtests (name, test_result_id) values ('subtest 14', 3);
insert into al_subtests (name, test_result_id) values ('subtest 14', 8);
insert into al_subtests (name, test_result_id) values ('subtest 10', 10);
insert into al_subtests (name, test_result_id) values ('subtest 8', 3);
insert into al_subtests (name, test_result_id) values ('subtest 2', 4);
insert into al_subtests (name, test_result_id) values ('subtest 2', 2);
insert into al_subtests (name, test_result_id) values ('subtest 4', 10);
insert into al_subtests (name, test_result_id) values ('subtest 13', 10);
insert into al_subtests (name, test_result_id) values ('subtest 5', 6);
insert into al_subtests (name, test_result_id) values ('subtest 8', 1);
insert into al_subtests (name, test_result_id) values ('subtest 13', 2);
insert into al_subtests (name, test_result_id) values ('subtest 7', 5);
insert into al_subtests (name, test_result_id) values ('subtest 13', 9);
insert into al_subtests (name, test_result_id) values ('subtest 7', 10);
insert into al_subtests (name, test_result_id) values ('subtest 3', 1);
insert into al_subtests (name, test_result_id) values ('subtest 14', 2);
insert into al_subtests (name, test_result_id) values ('subtest 2', 3);
insert into al_subtests (name, test_result_id) values ('subtest 11', 7);
insert into al_subtests (name, test_result_id) values ('subtest 9', 1);
insert into al_subtests (name, test_result_id) values ('subtest 8', 1);
insert into al_subtests (name, test_result_id) values ('subtest 12', 8);
insert into al_subtests (name, test_result_id) values ('subtest 7', 3);
insert into al_subtests (name, test_result_id) values ('subtest 7', 10);
insert into al_subtests (name, test_result_id) values ('subtest 5', 1);
insert into al_subtests (name, test_result_id) values ('subtest 6', 3);
insert into al_subtests (name, test_result_id) values ('subtest 4', 6);
insert into al_subtests (name, test_result_id) values ('subtest 3', 5);
insert into al_subtests (name, test_result_id) values ('subtest 1', 8);
insert into al_subtests (name, test_result_id) values ('subtest 5', 5);
insert into al_subtests (name, test_result_id) values ('subtest 1', 1);
insert into al_subtests (name, test_result_id) values ('subtest 3', 9);
insert into al_subtests (name, test_result_id) values ('subtest 4', 1);
insert into al_subtests (name, test_result_id) values ('subtest 7', 6);
insert into al_subtests (name, test_result_id) values ('subtest 15', 9);
insert into al_subtests (name, test_result_id) values ('subtest 8', 7);
insert into al_subtests (name, test_result_id) values ('subtest 4', 7);
insert into al_subtests (name, test_result_id) values ('subtest 10', 5);
insert into al_subtests (name, test_result_id) values ('subtest 7', 4);
insert into al_subtests (name, test_result_id) values ('subtest 3', 3);
insert into al_subtests (name, test_result_id) values ('subtest 9', 9);
insert into al_subtests (name, test_result_id) values ('subtest 12', 2);
insert into al_subtests (name, test_result_id) values ('subtest 8', 7);

insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (19, 4, 3, 1, 2, 'Rep anulus fibrosus-grft');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (38, 22, 1, 4, 2, 'Remove ext mand fix dev');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (26, 17, 3, null, null, 'Digital rectal exam');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (72, 17, 5, 3, 2, 'Pros rep ventric def-opn');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (93, 11, 5, 3, 1, 'Salpingo-oophorostomy');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (13, 6, 4, null, 2, 'Rabies vaccination');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (24, 26, 5, 3, 2, 'Intravasclr spectroscopy');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (67, 22, 2, null, 2, 'Corneal scrape for smear');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (96, 28, 5, 1, 3, 'Hand muscle reattachment');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (99, 21, 4, null, 1, 'Destruct cornea les NEC');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (39, 19, 3, null, null, 'Alcoholism counselling');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (8, 34, 3, 1, null, 'Oth rep int cervical os');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (66, 19, 1, 2, null, 'Vacuum extract del NEC');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (12, 29, 4, 3, null, 'Limb short proc-femur');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (51, 33, 3, 1, null, 'Lap abdperneal resc rec');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (39, 38, 4, 3, 3, 'Nasal les destruct NEC');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (100, 16, 2, 2, 1, 'Contrast renal arteriogr');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (74, 28, 2, null, 2, 'Omt to move tissue fluid');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (57, 32, 1, 4, 3, 'Endometrial ablation');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (47, 33, 1, 1, 3, 'Breast thermography');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (2, 39, 1, null, 1, 'Opn reduc disloc-shouldr');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (81, 29, 5, 1, null, 'Below knee amputat NEC');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (8, 17, 1, 1, 2, 'Pelvic dye contrast xray');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (81, 16, 2, 1, 1, 'Tendon trnsfr/transplant');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (60, 34, 4, 2, null, 'Facial bone reconstr NEC');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (62, 10, 3, 4, 3, 'Tm contrast arthrogram');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (68, 39, 3, null, 3, 'Midtarsal fusion');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (13, 22, 2, 1, 3, 'Parasitology-endocrine');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (65, 17, 3, 1, null, 'Removal scrotal/penis FB');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (69, 38, 5, 3, null, 'Refusion of atlas-axis');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (2, 13, 1, null, null, 'Ins part disc pros cerv');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (41, 40, 2, 2, 3, 'Ankle arthroscopy');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (87, 24, 4, 1, 1, 'Temp-inf intrcap lens ex');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (74, 29, 4, null, null, 'Excise femur for graft');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (71, 28, 5, 1, 3, 'Rad subtot pancreatectom');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (52, 32, 2, null, 2, 'Remov retroperiton drain');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (95, 15, 5, 1, null, 'Laser destruc rectal les');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (34, 37, 1, 2, 1, 'Open reduction-femur fx');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (81, 18, 2, 4, 2, 'Excise patella for graft');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (65, 2, 5, null, null, 'Pineal field exploration');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (40, 12, 2, 1, 2, 'Exploratory thoracotomy');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (7, 15, 3, 1, null, 'Other dx pt procedure');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (28, 4, 5, 4, 3, 'Bone graft to face bone');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (43, 16, 2, 1, 2, 'Prosth rep hrt septa NOS');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (74, 30, 3, 3, 2, 'Culture-lower GI');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (60, 15, 3, null, 1, 'Open coronry angioplasty');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (38, 16, 2, 4, null, 'Tendon reattachment');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (33, 6, 5, null, 1, 'Nasal function study');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (26, 11, 4, 2, 3, 'Lymph structure op NEC');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (28, 5, 5, 4, 2, 'Amputat through malleoli');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (64, 25, 5, 1, 2, 'Nasal repair NEC');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (37, 30, 1, 1, 1, 'Impl or rev art anal sph');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (25, 27, 4, 2, 3, 'Bilat endos occ tube NEC');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (32, 21, 2, null, null, 'Open adrenal gland bx');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (80, 17, 3, 1, 1, 'Lap radical abdomnl hyst');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (77, 17, 4, 3, 1, 'Cyclophotocoagulation');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (1, 31, 4, 2, 2, 'Auto hem stem ct w purg');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (21, 34, 1, null, 1, 'Tenotomy of hand');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (33, 37, 2, 2, 2, 'Sm bowel exteriorization');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (64, 24, 1, 1, 1, 'Urethral sphincter emg');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (66, 17, 4, 3, null, 'Revis extraoc musc surg');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (54, 32, 2, 4, 2, 'Delay opening colostomy');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (39, 40, 5, 3, 3, 'Wrist arthroscopy');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (10, 31, 3, 4, null, 'Parasitology-lymph sys');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (53, 22, 1, 4, 1, 'Rhythm electrocardiogram');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (8, 11, 1, 1, null, 'Replace gast/esoph tube');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (81, 6, 1, 2, 2, 'Inj/inf platelet inhibit');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (19, 26, 1, 1, null, 'Periph nerv anastom NEC');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (63, 38, 1, 3, 1, 'Arterioven fistula rep');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (50, 32, 5, 4, 2, 'Cl fx reduc-int fix NOS');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (96, 23, 2, 3, null, 'Remove imp device-femur');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (34, 16, 5, 2, null, 'SIEA flap, free');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (68, 3, 2, 1, 2, 'Gastroenterostomy NEC');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (80, 2, 1, 2, 2, 'Fit lo arm/hand prosthes');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (22, 25, 5, 4, 2, 'Oth uni salpingo-oophor');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (52, 29, 5, null, 1, 'Other parathyroidectomy');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (29, 7, 3, null, 2, 'Periren/ureter incis NEC');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (12, 12, 3, 4, 2, 'Total unilat salpingect');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (59, 39, 3, 2, 1, 'Clipping of aneurysm');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (11, 39, 1, 2, 1, 'Temp endovsc occls vessl');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (1, 35, 5, 1, 1, 'Abdomen artery incision');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (61, 38, 1, 3, 1, 'Lap adhesiolys ova/tube');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (6, 23, 1, null, null, 'Humerus biopsy');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (69, 24, 4, 4, null, 'Cerebral thermography');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (14, 11, 1, null, 1, 'Other CAS');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (37, 4, 2, 3, 3, 'Lap mul seg res lg intes');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (49, 14, 1, 1, null, 'High gastric bypass');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (55, 36, 3, 3, 3, 'Humerus injury op NOS');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (70, 5, 4, 1, 2, 'Common duct excis NEC');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (53, 16, 3, null, 3, 'Cholangiogram NEC');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (95, 7, 3, 1, null, 'Subarach-periton shunt');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (4, 25, 5, 3, 3, 'Destruct joint les NEC');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (41, 28, 4, 1, null, 'Closed fx reduction NEC');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (38, 36, 1, 3, null, 'Sympath nerve division');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (17, 28, 5, 4, 2, 'Imp cardiomyostimul sys');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (82, 4, 2, 4, null, 'Destruction lid lesion');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (39, 27, 1, 1, 1, 'Bladder exstrophy repair');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (76, 14, 2, 4, null, 'Repair of thymus');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (63, 36, 5, 4, null, 'Manual rotat fetal head');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (1, 29, 4, null, 2, 'Peritoneal suture');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (1, 10, 5, 3, 1, 'Toxic effects of carbon tetrachloride');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (2, 56, 4, 3, 1, 'Unspecified occupant of three-wheeled motor vehicle injured in collision with unspecified motor vehicles in traffic accident, initial encounter');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (3, 14, 5, 2, null, 'Malignant neoplasm of connective and soft tissue of right upper limb, including shoulder');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (4, 31, 5, 2, 3, 'Puncture wound without foreign body of right forearm, sequela');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (5, 37, 3, 2, 3, 'Salter-Harris Type II physeal fracture of right calcaneus, sequela');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (6, 22, 2, 4, 2, 'Corrosion of second degree of female genital region, initial encounter');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (7, 51, 3, 1, null, 'Subluxation of proximal interphalangeal joint of unspecified finger, subsequent encounter');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (8, 11, 5, 2, 3, 'Displaced transverse fracture of shaft of right ulna, initial encounter for open fracture type I or II');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (9, 17, 4, 2, null, 'Blizzard (snow)(ice), initial encounter');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (10, 58, 2, 2, null, 'Family history of tobacco abuse and dependence');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (11, 55, 2, 1, 2, 'Unspecified physeal fracture of lower end of humerus, left arm, subsequent encounter for fracture with delayed healing');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (12, 52, 4, 2, null, 'Displaced fracture of proximal phalanx of left great toe');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (13, 14, 3, null, 1, 'Nondisplaced transverse fracture of shaft of right tibia');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (14, 16, 2, 4, 2, 'Superficial frostbite of unspecified foot, initial encounter');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (15, 38, 5, 4, null, 'Nondisplaced apophyseal fracture of unspecified femur, subsequent encounter for closed fracture with malunion');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (16, 29, 1, 3, null, 'Melanoma in situ of ear and external auricular canal');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (17, 53, 1, 3, 2, 'Sprain of other ligament of right ankle');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (18, 41, 2, 2, 1, 'Crohn''s disease of large intestine with other complication');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (19, 22, 2, 1, 2, 'Disturbances of potassium balance of newborn');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (20, 39, 4, 3, 1, 'Nondisplaced midcervical fracture of unspecified femur, sequela');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (21, 16, 5, 1, null, 'Other specified osteochondropathies, right shoulder');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (22, 10, 4, 4, null, 'Other specified erythematous conditions');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (23, 55, 1, 4, 3, 'Laceration without foreign body of abdominal wall, left lower quadrant without penetration into peritoneal cavity, initial encounter');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (24, 18, 2, 4, 2, 'Stenosis of other vascular prosthetic devices, implants and grafts, sequela');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (25, 60, 3, 4, 3, 'Oligomenorrhea, unspecified');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (26, 25, 3, 1, 3, 'Other specified diabetes mellitus with severe nonproliferative diabetic retinopathy without macular edema');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (27, 42, 3, null, 2, 'Right lower quadrant rebound abdominal tenderness');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (28, 38, 2, 1, 2, 'Laceration of popliteal artery, left leg, sequela');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (29, 25, 2, null, 3, 'Malignant (primary) neoplasm, unspecified');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (30, 44, 3, 2, 3, 'Military operations involving explosion due to accidental detonation and discharge of own munitions or munitions launch device, military personnel, sequela');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (31, 11, 2, 4, 1, 'Anaphylactic shock, unspecified');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (32, 11, 5, 3, 3, 'Supervision of pregnancy with history of in utero procedure during previous pregnancy, second trimester');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (33, 13, 2, 3, 2, 'Exposure to other furniture fire due to unspecified burning material, initial encounter');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (34, 36, 3, 2, 2, 'Activities involving exterior property and land maintenance, building and construction');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (35, 25, 5, null, 3, 'Palindromic rheumatism, unspecified knee');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (36, 31, 2, null, 1, 'Unspecified fall due to ice and snow');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (37, 27, 2, 2, 2, 'Unspecified fracture of unspecified patella, sequela');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (38, 44, 3, 2, null, 'Strain of flexor muscle, fascia and tendon of right ring finger at wrist and hand level, sequela');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (39, 15, 1, 2, 1, 'Burn of third degree of upper back, initial encounter');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (40, 14, 3, 2, 3, 'Vertical strabismus, left eye');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (41, 15, 4, 3, 3, 'Displaced oblique fracture of shaft of unspecified tibia, initial encounter for closed fracture');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (42, 60, 1, 3, null, 'Attic perforation of tympanic membrane, unspecified ear');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (43, 36, 4, 3, null, 'Poisoning by unspecified narcotics, intentional self-harm, initial encounter');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (44, 52, 3, 3, 2, 'Hypertensive retinopathy, bilateral');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (45, 3, 3, 2, 1, 'Other chronic osteomyelitis, unspecified site');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (46, 48, 4, null, 3, 'Polyclonal hypergammaglobulinemia');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (47, 17, 2, 4, 3, 'Congenital malformation of skin, unspecified');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (48, 44, 1, 4, 2, 'Nondisplaced segmental fracture of shaft of unspecified tibia, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with delayed healing');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (49, 9, 5, 1, null, 'Periprosthetic fracture around other internal prosthetic joint, sequela');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (50, 41, 3, null, 1, 'Displaced fracture of shaft of other metacarpal bone, subsequent encounter for fracture with routine healing');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (51, 57, 5, 1, 3, 'Idiopathic chronic gout, hip');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (52, 15, 5, 3, 3, 'Parachutist accident');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (53, 43, 1, 1, 1, 'Fracture of unspecified part of body of left mandible, subsequent encounter for fracture with delayed healing');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (54, 48, 1, 3, 1, 'Chondromalacia patellae, unspecified knee');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (55, 36, 2, 2, 1, 'Toxic effect of unspecified noxious substance eaten as food, assault, initial encounter');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (56, 6, 3, 4, 2, 'Displaced segmental fracture of shaft of ulna, unspecified arm, subsequent encounter for closed fracture with delayed healing');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (57, 59, 2, null, 2, 'Poisoning by ganglionic blocking drugs, accidental (unintentional), initial encounter');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (58, 11, 1, null, 1, 'Military operations involving chemical weapons and other forms of unconventional warfare, civilian');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (59, 20, 3, 2, 2, 'Poisoning by saline and osmotic laxatives, intentional self-harm, sequela');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (60, 5, 3, 2, 2, 'Infection of amniotic sac and membranes, unspecified, second trimester, fetus 5');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (61, 52, 2, 3, 1, 'Nondisplaced fracture of posterior wall of unspecified acetabulum');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (62, 43, 2, 2, 1, 'Poisoning by rifampicins, undetermined, subsequent encounter');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (63, 7, 1, 2, 3, 'Ankylosing hyperostosis [Forestier], sacral and sacrococcygeal region');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (64, 25, 5, 4, 3, 'Unspecified premature depolarization');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (65, 26, 4, 4, 1, 'Other secondary parkinsonism');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (66, 47, 5, 3, 2, 'Unspecified injury of unspecified blood vessel at wrist and hand level of left arm, initial encounter');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (67, 55, 3, 4, 1, 'Sprain of unspecified site of unspecified knee, subsequent encounter');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (68, 28, 2, 2, null, 'Intentional self-harm by drowning and submersion while in bathtub');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (69, 47, 2, 1, null, 'Open bite, right hip');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (70, 9, 2, null, 2, 'Unspecified injury of intercostal blood vessels, right side, sequela');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (71, 59, 5, 3, 3, 'Injury of digital nerve of left ring finger, sequela');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (72, 53, 3, 4, null, 'Displaced spiral fracture of shaft of ulna, left arm, subsequent encounter for closed fracture with routine healing');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (73, 41, 3, 4, 3, 'Other fracture of upper end of unspecified ulna, subsequent encounter for open fracture type I or II with delayed healing');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (74, 55, 5, 3, null, 'Salter-Harris Type IV physeal fracture of lower end of tibia');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (75, 35, 4, 4, null, 'Stress fracture, left toe(s), sequela');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (76, 50, 3, 2, 1, 'Laceration of left renal vein, sequela');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (77, 11, 3, null, 2, 'Fracture of bony thorax, part unspecified, subsequent encounter for fracture with delayed healing');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (78, 22, 3, 1, 3, 'Infection of amputation stump, left lower extremity');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (79, 17, 5, 1, 2, 'Abrasion of right hand, subsequent encounter');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (80, 55, 3, 3, 2, 'Nondisplaced segmental fracture of shaft of ulna, left arm, subsequent encounter for open fracture type I or II with routine healing');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (81, 8, 1, 3, 3, 'Sarcoidosis of other sites');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (82, 54, 1, 4, 1, 'Poisoning by predominantly alpha-adrenoreceptor agonists, assault, initial encounter');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (83, 30, 5, null, 3, 'Burn of second degree of unspecified site of left lower limb, except ankle and foot, initial encounter');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (84, 53, 5, 1, 2, 'Struck by other psittacines');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (85, 3, 4, 1, 1, 'Displaced avulsion fracture (chip fracture) of left talus, subsequent encounter for fracture with malunion');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (86, 7, 3, 3, 1, 'Preterm premature rupture of membranes, onset of labor more than 24 hours following rupture, second trimester');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (87, 27, 5, 2, null, '3-part fracture of surgical neck of unspecified humerus, subsequent encounter for fracture with routine healing');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (88, 34, 2, 3, 3, 'Other osteoporosis with current pathological fracture, right humerus, subsequent encounter for fracture with malunion');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (89, 19, 2, 2, 2, 'Adverse effect of unspecified agents primarily affecting the cardiovascular system, subsequent encounter');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (90, 58, 1, 3, 1, 'Other secondary gout, left wrist');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (91, 44, 5, 3, 1, 'Unspecified injury of celiac artery, initial encounter');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (92, 33, 4, 1, 2, 'Displaced fracture of proximal phalanx of other finger, subsequent encounter for fracture with nonunion');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (93, 44, 4, 3, null, 'Stenosis of bilateral lacrimal sac');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (94, 55, 2, 4, 1, 'Person on outside of three-wheeled motor vehicle injured in noncollision transport accident in traffic accident, initial encounter');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (95, 29, 4, 3, 2, 'Passenger in three-wheeled motor vehicle injured in collision with railway train or railway vehicle in nontraffic accident, subsequent encounter');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (96, 18, 3, null, 2, 'Laceration of other part of small intestine, sequela');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (97, 23, 1, 3, 1, 'Open-angle glaucoma');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (98, 49, 5, 4, 2, 'Other superficial bite of left little finger, initial encounter');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (99, 16, 2, 1, 2, 'Chronic instability of knee');
insert into al_teststeps (step_no, subtest_id, result_type_id, error_id, warning_id, result_details) values (100, 15, 5, 2, 2, 'Lichen planus, unspecified');